
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files # Prevent giant files to be committed (default  > 500kB)
          - id: check-ast # Check files parse as valid Python
            exclude: ^(dags/).+(.py)$
          - id: check-builtin-literals
          - id: check-docstring-first # Checks for a common error of placing code before the docstring.
          - id: check-yaml # Attempts to load all yaml files to verify syntax.
            args: ["--unsafe"]
          - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
            exclude: ^(dags/).+(.py)$
          - id: detect-private-key
          - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
          - id: mixed-line-ending # Replaces or checks mixed line ending. (Linux-only)
            args: ["--fix", "lf"]
          - id: name-tests-test # Verifies that test files are named correctly.
            args: ["--pytest-test-first"]
          - id: no-commit-to-branch # Protect specific branches from direct checkins.
            args: ["--branch", "production"]
          - id: requirements-txt-fixer # Sorts entries in requirements.txt and removes incorrect entries
          - id: trailing-whitespace # Trims trailing whitespace.
            args: [--markdown-linebreak-ext=md]
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            exclude: ^(dags/).+(.py)$
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            args: [--ignore, "W391, E501,W503,E302,E402,E203"]
            # W391: blank line at end of file
            # 501: line length; W503: line break before bop; E302: expected line breaks,
            # E402: import order, E203: whitespace before ';'
    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
          - id: detect-secrets
            args:
                [
                    "--baseline",
                    ".detect.baseline",
                    "--exclude-lines",
                    '"(hash|id|image/\w+)":.*',
                ]
            exclude: .*/tests/*|.*/.secrets.toml
    - repo: https://github.com/iterative/dvc
      rev: main
      hooks:
          - id: dvc-pre-commit
            language_version: python3
            stages:
                - commit
